spring:
  application:
    name: serverconfig
  cloud:
    config:
      server:
        git:
          uri: D:\Bitbucket\Spring\workspace_spring_cloud\Repo_Git_Config
security:
  user:
    password: mipassword
server:
  port: 8082
  