spring:
  application:
    name: serverconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorherrerocazurro/RepositorioConfiguraciones
security:
  user:
    password: mipassword
server:
  port: 8082
  